annotations_dir: '/root/workspace/dataset_2022/metadata_dev/dev-test-sony'
audio_dir: '/root/workspace/dataset_2022/mic_dev/dev-test-sony'
preprocessed_data_dir : '/root/workspace/dataset_2022/mic_dev/preprocessed_dir'
sample_rate: 22050
num_samples: 22050
transforms:
  - type: STFT
    n_fft: 1024
    hop_length: 512
    window: 'hann'
